apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-env
  namespace: celery
data:
  POSTGRES_USER: postgres
  POSTGRES_SERVER: postgres-postgresql.postgres.svc.cluster.local:5432
  REDIS_SERVER: redis.redis.svc.cluster.local:6379/0
  FLASK_APP: app.py
  CELERY_BROKER_URL: redis-sentinel://redis.redis.svc.cluster.local:26379 # for flower
  FLOWER_PORT: '8080'
