apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: keda
  name: keda
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kedacore.github.io/charts
    targetRevision: v2.8.1
    path: ""
    chart: keda
    helm:
      version: v3
      values: |
        logging:
          operator:
            level: debug
        operator:
          replicaCount: 1
  destination:
    name: in-cluster
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: keda-added-resources
  name: keda-added-resources
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jmacku/keda
    path: argocd/custom/keda/
  destination:
    name: in-cluster
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m