apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: postgres
  name: postgres
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: v11.8.1
    path: ""
    chart: postgresql
    helm:
      version: v3
      values: |
        auth:
          postgresPassword: "postgres"
  destination:
    name: in-cluster
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
