apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: v39.9.0
    path: ""
    chart: kube-prometheus-stack
    helm:
      version: v3
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
